# Generated by Django 4.2.2 on 2023-06-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('P_Id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.DateField(auto_now=True)),
                ('Promt_message', models.TextField(blank=True, max_length=5000)),
                ('Response', models.TextField(blank=True, max_length=500000)),
            ],
        ),
    ]
